-- AlterTable
ALTER TABLE "App" ADD COLUMN     "frequencyPenalty" DOUBLE PRECISION,
ADD COLUMN     "maxTokens" INTEGER,
ADD COLUMN     "modelName" TEXT NOT NULL DEFAULT 'gpt-3.5-turbo',
ADD COLUMN     "n" INTEGER NOT NULL DEFAULT 1,
ADD COLUMN     "openAIApiKey" TEXT,
ADD COLUMN     "presencePenalty" DOUBLE PRECISION,
ADD COLUMN     "stop" TEXT[] DEFAULT ARRAY[]::TEXT[],
ADD COLUMN     "streaming" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "timeout" INTEGER NOT NULL DEFAULT 3000,
ADD COLUMN     "topP" DOUBLE PRECISION,
ADD COLUMN     "user" TEXT;
