import config_ from "./config.json" assert { type: "json" }

export const config = config_
config.version = process.env.npm_package_version ?? "0.1.0"

// export * from "./api-client"
// export * from "./bilibili"
// export * from "./const"
// export * from "./datetime"
// export * from "./db"
// export * from "./dev"
// export * from "./env"
// export * from "./extend-tv"
// export * from "./file"
// export * from "./font"
// export * from "./hooks"
// export * from "./html"
// export * from "./i18n"
export * from "./log"
// export * from "./markdown"
// export * from "./oss"
// export * from "./path"
// export * from "./pusher"
// export * from "./sample"
// export * from "./schema"
// export * from "./spider"
// export * from "./sse"
// export * from "./state-management"
// export * from "./store"
// export * from "./transport"
// export * from "./utils"
// export * from "./visualization"
// export * from "./xhs"
